### ISSUE TITLE
Add WS compression to the WiSH spec

### ISSUE THREAD

**Issue by wenbozhu** [bidiweb/wish#11]
As discussed, this is an important feature to support, given it's already widely adopted in WS etc.

**Comment by tyoshino** [comment]
So, we need to again try to include the way to negotiate the compression feature.

For WebSocket/TCP, it uses Sec-WebSocket-Extensions.  In similar way or use the Content-Type/Accept.

**Comment by wenbozhu** [comment]
Shouldn't we use content-encoding and accept-encoding?

What if we reserve two bits (4 compression types) or 3 bits (8 compression types), including identity, and remove the need for Accept-Encoding (i.e. assuming symmetric choices) ?

00: identity
01: gzip
02/3: reserved

E.g. if the client sends 01 (gzip), the server may use 00, 01, or 0x which may cause the request to abort.

**Comment by wenbozhu** [comment]
I took back my 2nd suggestion. 

Ye,s we should just use all the headers already defined for WS/TCP.

**Comment by tyoshino** [comment]
Yeah, use of the bits in frames would effectively makes some part of the body negotiation. It also has a problem that without introducing no-op frame, one side needs to send a frame just for getting agreement on the compression.

----

We could use the content codings (Content-Encoding/Accept-Encoding) to carry the information, but it's going to be specific to the WiSH MIME type.

I see some existing content codings in the IANA registry (e.g. exi, and maybe pack200-gzip too?) that are specific to a certain MIME type.
https://www.iana.org/assignments/http-parameters/http-parameters.xhtml#content-coding

But basically I feel that such an information should be considered as a part of the MIME type and negotiated inside the Content-Type/Accept headers.

----

Unlike the `protocol` parameter which carries the `Sec-WebSocket-Protocol` header data of the WebSocket protocol each item in which is guaranteed to be a `token`, permessage-deflate extension descriptor used in the `Sec-WebSocket-Extensions` header is a structure containing a few parameters.

Shall we flatten these too to the list of MIME types?

**Comment by tyoshino** [comment]
In WebSocket protocol, the subprotocol negotiation was a separate dimension. It's still offered in the Accept header as an independent dimension, but listed together with the MIME type.

```
Accept: application/web-stream; protocol=foo; q=1,
    application/web-stream; protocol=bar; q=0.5
```

To negotiate the compression parameters in this framework, we need to list all the available compression descriptors for each of the acceptable type descriptors.

```
Accept: application/web-stream; protocol=foo; compression="deflate; client_max_window_bits",
    application/web-stream; protocol=foo; compression="brotli",
    application/web-stream; protocol=bar; compression="deflate; client_max_window_bits",
    application/web-stream; protocol=bar; compression="brotli"
```

**Comment by wenbozhu** [comment]
Re: using C-T/Accept, then we don't really need the compress bit in the frame, right? I am OK with such a simplification. 

So basically we will have an informal section on how to do content-negotiation in general, which is outside the scope of the core WiSH spec.

**Comment by wenbozhu** [comment]
Thanks for the example. I saw duplicated lines .. or they are intended?

**Comment by tyoshino** [comment]
https://github.com/bidiweb/wish/issues/11#issuecomment-288632290 makes me think about Content-Encoding again.

> Re: using C-T/Accept, then we don't really need the compress bit in the frame, right? I am OK with such a simplification.

For the WebSocket protocol, the compression bit was introduced to turn on/off compression message-wise as single WebSocket connection may carry multiple types of messages where some of them are compressible but the others are not.

**Comment by tyoshino** [comment]
> Thanks for the example. I saw duplicated lines .. or they are intended?

Sorry, fixed!

**Comment by tyoshino** [comment]
> So basically we will have an informal section on how to do content-negotiation in general, which is outside the scope of the core WiSH spec.

I see. Yeah, if we have negotiation, it'll be out of the scope. If we mandate some compression, we could use the bits and have everyone implement the mandatory compression.

**Comment by wenbozhu** [comment]
https://github.com/bidiweb/wish/issues/11#issuecomment-288633199 

You are right. C-T/Accept and compression bits are not exclusive, but C-E is.

Since WS already supports compression bit (e.g. smaller messages should not be compressed), we should 
1) add the compression bit
2) provide an example for compression content-negotiation

**Comment by tyoshino** [comment]
https://github.com/bidiweb/wish/issues/11#issuecomment-288633199

Sorry again. About C-E, I remember that there was some discussion that we could allow listing non-WiSH MIMEs together with WiSH MIME ones in the Accept header. In that case, if we use C-E for listing compression for WiSH, they'll be meaningless when some of the non-WiSH MIMEs is chosen. Maybe ok, but wanna check what do you feel with this.

**Comment by wenbozhu** [comment]
A-E and Accept are two separate dimensions, so I think it's OK to have the following:

Accept: webstream, jsonstream
Accept-Encoding: webstream-gzip  

if webstream-gzip is a registered encoding types.

**Comment by tyoshino** [comment]
https://github.com/bidiweb/wish/issues/11#issuecomment-288634246 sounds good.

**Comment by tyoshino** [comment]
https://github.com/bidiweb/wish/issues/11#issuecomment-288635427 OK. So, the endpoints just exclude non-applicable compression choices once the type to accept is determined.

**Comment by wenbozhu** [comment]
To summarize:

C-T and Accept: protocol negotiation, example only
C-E and A-E: compression negotiation, example only for the WiSH spec, but we may register those webstream-* types with a separate I-D, including how to cover RFC 7692 (windows-bit etc)

Compression bit: required as part of the core framing.

**Comment by tyoshino** [comment]
lgtm!

**Comment by tyoshino** [comment]
Added via #14

**Comment by wenbozhu** [comment]
Thanks.
