### ISSUE TITLE
Write a spec on how WiSH negotiation may work from browsers

### ISSUE THREAD

**Issue by wenbozhu** [bidiweb/wish#12]
A rough draft is sufficient, which we may link to from the WiSH I-D.

**Comment by tyoshino** [comment]
Here's a very basic strawman

- a server may emit some header indicating WiSH availability e.g. "WebSocket-Alternative: WiSH; maxage=86400", this covers only WS that is same-origin to the page who initiate the WS
- for corss-origin, e.g a site http://example.com connecting ws://foo.com/socket, http://example.com may emit "WebSocket-Alternative" header with "origin=foo.com" which suggests the user-agent to first send a CORS preflight to "foo.com" in response to which "foo.com" may emit "WebSocket-Alternative".
- apply HTTP's CORS for cross-origin. No WiSH specific cross-protocol attack prevention, handshake
- use Content-Type, Accept for content negotiation (subprotocol of WebSockets) as we've been discussing at HTTP WG ML

**Comment by wenbozhu** [comment]
Could we copy this to an md file (handshake.md) alongside the spec draft in bidiweb ,and then add a link in the wish I-D to this doc?

**Comment by wenbozhu** [comment]
Is this proposal specific to Web API (i.e. WS API), or user library could adopt the same approach?

If the former, let's remove the link for I-D.

**Comment by tyoshino** [comment]
Done by adding new opcodes https://github.com/bidiweb/wish/pull/18

**Comment by tyoshino** [comment]
Created an MD file
https://github.com/bidiweb/wish/blob/master/ws-over-wish.md

**Comment by wenbozhu** [comment]
Nice. Thanks.

**Comment by tyoshino** [comment]
Added a link to the MD by https://github.com/bidiweb/wish/commit/bc2f2821f96030331d883c6076d3c7e94c25c456

**Comment by tyoshino** [comment]
> Is this proposal specific to Web API (i.e. WS API), or user library could adopt the same approach?

The new idea in the MD is specific to web browsers as it assumes there is a web page initiating a WebSocket and it uses the HTTP response for the web page to announce capability.

What non-browser libraries would use is explained in the draft-yoshino-ws-over-wish I-D.
