### ISSUE TITLE
Update API binding details in the I-D

### ISSUE THREAD

**Issue by tyoshino** [bidiweb/wish#16]
The story in the I-D is currently fetch()/Streams based Polyfilling of the WebSocket API. Update it to reflect recent discussion.

**Comment by wenbozhu** [comment]
As discussed, let's remove WS API from the I-D to avoid future confusion.

**Comment by tyoshino** [comment]
The texts about WS API binding has been moved to a new separate I-D draft-yoshino-ws-over-wish.xml.
