### ISSUE TITLE
Terminology: WiSH stands for framing or high level concept?

### ISSUE THREAD

**Issue by tyoshino** [bidiweb/wish#22]
Branched from https://github.com/bidiweb/wish/pull/19#discussion_r115327234

**Comment by wenbozhu** [comment]
High-level concept (or really just a code name for the overall effort).

So, IMO, in any specs we should avoid using WiSH. Specifically for the framing, "the web-stream format"  should be used to refer to the framing spec. 

Thoughts?

**Comment by tyoshino** [comment]
I see. It would work, too.

`The web-stream format` sounds good. Or `The Web stream format`?

cf. https://www.iana.org/assignments/media-types/media-types.xhtml

**Comment by wenbozhu** [comment]
"web-stream" preferred, but your call. It's more like "form-data" etc.
