### ISSUE TITLE
Seoul (Nov. 13, IETF-97) HTTP WG

### ISSUE THREAD

**Issue by benjchristensen** [bidiweb/wish#3]
It has been mentioned that this topic will be discussed at the next HTTP WG in Nov in Seoul. 

What preparation needs to be done for that? Are all attendees already confirmed, or would it be beneficial to have others come to support this discussion?

**Comment by wenbozhu** [comment]
I think we should try to finalize the discussion on WiSH and reactivesocket over HTTP/2 first. Maybe both specs are needed, to address different use cases.

The session will be announced probably soon. If we feel strongly about pushing forward a formal proposal, I think it would be beneficial to attend in person.

**Comment by wenbozhu** [comment]
https://github.com/httpwg/wg-materials/blob/gh-pages/ietf97/agenda.md
