### ISSUE TITLE
Proposal of WebSocket2 over HTTP/2

### ISSUE THREAD

**Issue by benjchristensen** [bidiweb/wish#4]
This proposal was just published (Oct 1 2016): https://github.com/vans163/websocket2-drafts/blob/master/websocket2-over-http2.txt

It is seeking to achieve the same ultimate goals of bidirectional byte streams over HTTP/2. I think we should understand pros/cons of it vs WiSH and try and engage in discussion.

**Comment by tyoshino** [comment]
Yeah, as cited in the discussion, Yutaka of Chrome networking API team has been pursuing the way before. Since then, the web platform has evolved to gain more ability e.g. Fetch API and Streams API. So, we should investigate pros/cons again as you said given what we have now, right.

**Comment by wenbozhu** [comment]
Takeshi, could you have a closer look at the spec? 

I think it introduces a new protocol v.s. just a new MIME type (read: stateless).

# 

BTW, before HTTP/2 was finalized, the idea of an extended http/2 framing to support L7 messaging protocols (like WS) has also been captured here.

https://github.com/bidiweb/wish/blob/master/draft-zhu-httpbis-http2-protocol-layering-00.txt

**Comment by tyoshino** [comment]
I read the proposal. It's very similar to WiSH idea in terms of layering of message traffic, but regarding API design and handshake it's more like WebSocket/HTTP2.

Van's proposal:
- exchanges messages with the DATA frame as well as HTTP1.1/H2 layering
- uses framing different from WebSocket's one. 32bit fixed-size payload length header
- built-in compression feature with choice of algorithms: lz4 and deflate
- exchanges some special headers e.g. `websocket2-version` at the beginning (handshake)

**Comment by wenbozhu** [comment]
We should reveal the WiSH work again, now that you have commented on this proposal. We should mention that the proposal has been posted on bidiweb in July for discussing at the http workshop and is currently under discussion with other interested parties.

**Comment by tyoshino** [comment]
Done https://lists.w3.org/Archives/Public/ietf-http-wg/2016OctDec/0042.html

**Comment by wenbozhu** [comment]
Let's close this issue then. If you feel any specific concern needs be addressed related to the other proposal, please open a separate issue.

Of course,  the author is more than welcome to join the discussion here.
